### ISSUE TITLE
room / sponsor assignments

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-signs#67]
Thursday:
- Ballroom G/H: Postgres and Percona
- Ballroom A/B: Tigera, Uila, StormForge, Percona, Chronosphere, Red Hat, Attached QR Code
- Ballroom C: Canonical
- Ballroom F: Red Hat, SUSE
- Room 106: NixOS, Antithesis,PDT Partners, Flox, WorldQuant, Anduril, Replit, Tweag, Obsidian Systems, Determinate System, Garnix
- Room 212/214: KwaAI

Friday:
- Ballroom G/H: Postgres and Percona
- Ballroom A/B: Tigera, Uila, StormForge, Percona, Chronosphere, Red Hat, Attached QR Code
- Ballroom C: Canonical
- Ballroom DE: Victoria Metrics, Semaphore CI, Doppler, SolarWinds, HoneyComb, SigScalr, DNSimple, TrackIt, Everbridge, SauceLabs, Couchbase
- Room 101: NixOS, Antithesis,PDT Partners, Flox, WorldQuant, Anduril, Replit, Tweag, Obsidian Systems, Determinate System, Garnix
- Room 103: NixOS, Antithesis,PDT Partners, Flox, WorldQuant, Anduril, Replit, Tweag, Obsidian Systems, Determinate System, Garnix
- Room 106: Pingcap
- Room 209/210: Camunda & FreeBSD Foundation

**Comment by irabinovitch** [comment]
QR Code for Ballroom A/B ![kcd-survey-qr (1)](https://github.com/socallinuxexpo/scale-signs/assets/289654/c708ee81-0b2f-4914-8396-b3d2a0d342f1)

**Comment by irabinovitch** [comment]
CC @sarcasticadmin @carlynlee

**Comment by sarcasticadmin** [comment]
Adding a note here about adding specific room sponsors from @kylerisse original post to the tech mailing list:

An example of what a room page sponsor (`http://signs.scale.lan/?room=ballroom-de`)  would look like:
https://github.com/socallinuxexpo/scale-signs/blob/master/.README/room_view_sponsors.png
> The page cycles through the following pages -> Current/upcoming speaker -> Wifi + Sponsors -> Room sponsors

And is controlled by this array here:
https://github.com/socallinuxexpo/scale-signs/blob/dc7447f9902ddb41cd4f824e1905e0c2dc605c99/server/room.php#L243-346

Here's an example of when it was populated in the past: (for example DevOps
day 2020)
https://github.com/socallinuxexpo/scale-signs/blob/5dfcef0173f60e8c2228474bdc5df68e1c0d7d19/server/room.php#L259

**Comment by carlynlee** [comment]
I found the missing logos from google image searches and added them to my branch: [s://github.com/carlynlee/scale-signs/tree/sponsor_assignnments](https://github.com/carlynlee/scale-signs/tree/sponsor_assignnments)
I made references to the server/room.php and listed the logos in array() according to the day of week in your list.
![](https://files.slack.com/files-pri/T03N5F864-F06NKT72H1V/screenshot_2024-03-11_at_4.10.35_pm.png)
 From what I understood, the items in the array() are the names of the logos minus extensions in server/images/sponsors/ (https://github.com/socallinuxexpo/scale-signs/tree/master/server/images/sponsors). 

I tried viewing the room sponsors with the following URIs but I didn't see what was expected:
![](https://files.slack.com/files-pri/T03N5F864-F06NKT72H1V/screenshot_2024-03-11_at_4.10.35_pm.png)

![](https://files.slack.com/files-pri/T03N5F864-F06P2TY33TN/screenshot_2024-03-11_at_4.12.08_pm.png)
Can anyone see what might have gone wrong?

**Comment by kylerisse** [comment]
Hi @carlynlee, thanks for this branch, great so far. I'm going to pull it down and work on it some. We can pair on it once you're onsite.

**Comment by kylerisse** [comment]
https://github.com/socallinuxexpo/scale-signs/pull/68

**Comment by sarcasticadmin** [comment]
Closing as this was completed in #68
